apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: sb-helloworld
  name: sb-helloworld
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'sb-helloworld:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/suttiruk046/sb-helloworld.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'maven:alpine'
    type: Docker
  successfulBuildsHistoryLimit: 5


